name: CICD

on:
  workflow_dispatch:
    inputs:
      service:
        options:
          - all
          - sms_gate
          - balance
        required: true
        type: choice
        description: Choose which service to run

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx

    - name: Build and Push SMS Gate
      if: ${{ github.event.inputs.service == 'sms_gate' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_sms_gate
      with:
        context: ./
        file: ./SmsGateCms/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:sms_gate

    - name: Build and Push Balance
      if: ${{ github.event.inputs.service == 'balance' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_balance
      with:
        context: ./
        file: ./SmsGate.Balance.Hosting/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:sms_gate_balance

    # Verification step for SMS Gate
    - name: Verify SMS Gate
      if: ${{ github.event.inputs.service == 'sms_gate' || github.event.inputs.service == 'all' }}
      run: echo ${{ steps.docker_build_sms_gate.outputs.digest }}_sms_gate

    # Verification step for Balance
    - name: Verify Balance
      if: ${{ github.event.inputs.service == 'balance' || github.event.inputs.service == 'all' }}
      run: echo ${{ steps.docker_build_balance.outputs.digest }}_sms_gate_balance